### ISSUE TITLE
*May* have to shuffle contents of netif

### ISSUE THREAD

**Issue by malachib** [ourairquality/lwip#1]
Enabling/disabling of options seems to push netif->hwaddr around, which the espressif blobs won't tolerate.

As annoying as it is, perhaps our best bet is to identify the #define'd features that grow/shrink the struct before the hwaddr offset and move them off closer to the end.

I can verify that LWIP_IGMP and LWIP_NUM_NETIF_CLIENT_DATA features break the sdk_internal.h asserts, but it's not clear to me how it really manifests itself.

**Comment by ourairquality** [comment]
Can you just shuffle them around for now? Perhaps just moving new fields later in the netif struct. If you let me know what works then I'll apply that to the esp-open-rtos patch until things improve.

The hostname option was enabled by default to avoid that causing people issues with the hwaddr, and perhaps we could just enable more slots to avoid changes as people enable and disable options (just remove the #ifdefs) around these? So work out what is likely to be needed and the new hwaddr and apply that to the sdk.

Fwiw the locations in the sdk of all the hwaddr uses are known, they have already been patched in the sdk as lwip now wants 16-bit alignment and the default sdk was not, and a `cmp -l` will show the addresses. The `state` slot is earlier in the netif struct so might be less of a problem, but I can probably track those uses down too if necessary.

**Comment by ourairquality** [comment]
Having looked into this, it seems cleanest to just move the `state` and `hwaddr` slots to the start of the netif struct and I'll do that and update the patch, thanks.

**Comment by malachib** [comment]
OK; I see now it's so obvious why LWIP_NUM_NETIF_CLIENT_DATA   would cause issues, duh... it's part of an array def just a few lines before hwaddr.  How did I miss that?

Moving up the state and hwaddr is a pretty good idea.  Cleaner than shuffling things around

Seems like brute-forcing on certain features to offer up the padding might be one option too, so that we don't have to put in empty space.  Of course then we are committing to the code space too... 

Does IPV6 even work if it's turned out?  Just curious...

EDIT: I never got any errors on state.  Maybe just a little shuffling up of hwaddr will do?  Gonna try that myself...I guess that risks busting things if other options get turned on though right.

**Comment by ourairquality** [comment]
Fixed by moving the slots to the start of the netif struct. I problems persist please open another issue.

**Comment by malachib** [comment]
I posted the gist in the wrong spot, dangit.  Too late now, but here it is anyway
https://gist.github.com/malachib/82fb94734e0b85242231c3c99b7439b2

Thank you!

**Comment by malachib** [comment]
Wait......... I didn't know you could actually move the hwaddr/state fields like that!
Cool!!  I thought they were immobilized at their current offsets..........
